### ISSUE TITLE
Horizontal scrolling on a form page

### ISSUE THREAD

**Issue by vladpekh** [TRPLucy/trplucy.github.io#1]
**Just push $1,500,000 closer to the left for smaller devices.**

![screenshot_20160405-121936](https://cloud.githubusercontent.com/assets/1377208/14289482/f860551e-fb28-11e5-829b-7b1e2c8adfe0.png)

**Comment by jiaaomusic** [comment]
thanks! just fixed it by making the second label `float:right`
